version: "3.1"

# Cấu hình pipeline xử lý ngôn ngữ tự nhiên (NLU)
language: vi  # Tiếng Việt

pipeline:
  # Cấu hình cho ngôn ngữ Tiếng Việt
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: RegexEntityExtractor
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

# Cấu hình các chính sách (policies)
policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "utter_default"
    enable_fallback_prediction: True
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 100
